<a href="https://www.kaggle.com/code/jimschacko/nlp-spam-classifier?scriptVersionId=135354301" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
textdf = pd.read_csv('/kaggle/input/maildataset/mail_data.csv')

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
textdf

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
textdf.shape

(5572, 2)

In [5]:
textdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [6]:
textdf.isnull()

Category  Message
0        False    False
1        False    False
2        False    False
3        False    False
4        False    False
...        ...      ...
5567     False    False
5568     False    False
5569     False    False
5570     False    False
5571     False    False

[5572 rows x 2 columns]

In [7]:
textdf['Message'].loc[1000]

'Aight will do, thanks again for comin out'

In [8]:
import re
import nltk
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [9]:
ps = PorterStemmer()

In [10]:
corpus = []
for i in range(0,len(textdf)):
    review = re.sub('[^a-zA-z]', ' ', textdf['Message'][i])
    reciew = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [11]:
corpus

['Go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'Ok lar joke wif u oni',
 'free entri wkli comp win FA cup final tkt st may text FA receiv entri question std txt rate T C appli',
 'U dun say earli hor U c alreadi say',
 'nah I think goe usf live around though',
 'freemsg hey darl week word back I like fun still Tb ok xxx std chg send rcv',
 'even brother like speak they treat like aid patent',
 'As per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner As valu network custom select receivea prize reward To claim call claim code KL valid hour',
 'had mobil month U R entitl updat latest colour mobil camera free call the mobil updat Co free',
 'I gonna home soon want talk stuff anymor tonight k I cri enough today',
 'six chanc win cash from pound txt csh send cost p day day tsandc appli repli HL info',
 'urgent you week free membership prize jackpot txt word claim No T C www dbuk net lccltd pobo

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500, binary = True)
x = cv.fit_transform(corpus).toarray()

In [13]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [14]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
x.shape

(5572, 2500)

In [16]:
textdf.columns

Index(['Category', 'Message'], dtype='object')

In [17]:
y = pd.get_dummies(textdf['Category'])
y = y.iloc[:,1].values

In [18]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [19]:
y.shape

(5572,)

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.25 , random_state =0)

In [21]:
from sklearn.naive_bayes import MultinomialNB
spam_model = MultinomialNB().fit(x_train,y_train)

In [22]:
from sklearn.metrics import accuracy_score
y_pred = spam_model.predict(x_test)
score = accuracy_score(y_test,y_pred)
print(score)

0.9856424982053122


In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1208
           1       0.97      0.92      0.94       185

    accuracy                           0.99      1393
   macro avg       0.98      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393



**Same way we can do for TFIDF now we will move towards wrod2vec and avgword2vec**

In [24]:
import gensim

In [25]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmatizer

<WordNetLemmatizer>

In [26]:
nltk.download('wordnet')
corpus = []
for i in range(0,len(textdf)):
    review = re.sub('[^a-zA-z]', ' ', textdf['Message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [27]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [28]:
corpus[0]

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [29]:
corpus[20]

'serious spell name'

In [30]:
words = []
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [31]:
words

[['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entri',
  'wkli',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'st',
  'may',
  'text',
  'fa',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'appli'],
 ['dun', 'say', 'earli', 'hor', 'alreadi', 'say'],
 ['nah', 'think', 'goe', 'usf', 'live', 'around', 'though'],
 ['freemsg',
  'hey',
  'darl',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chg',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['winner',
  'valu',
  'network',
  'custom',
  'select',
  'receivea',
  'prize',
  'reward',
  

In [32]:
model = gensim.models.Word2Vec(words,window=5,min_count=2)

In [33]:
model.wv.index_to_key

['call',
 'go',
 'get',
 'ur',
 'gt',
 'lt',
 'come',
 'day',
 'ok',
 'free',
 'know',
 'love',
 'like',
 'time',
 'want',
 'good',
 'got',
 'text',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'take',
 'see',
 'stop',
 'home',
 'think',
 'repli',
 'lor',
 'sorri',
 'tell',
 'still',
 'mobil',
 'back',
 'da',
 'dont',
 'make',
 'phone',
 'pleas',
 'say',
 'hi',
 'week',
 'new',
 'work',
 'later',
 'pl',
 'hope',
 'miss',
 'ask',
 'co',
 'msg',
 'min',
 'meet',
 'night',
 'dear',
 'messag',
 'happi',
 'wait',
 'well',
 'give',
 'tri',
 'thing',
 'much',
 'great',
 'oh',
 'claim',
 'wat',
 'hey',
 'number',
 'thank',
 'friend',
 'ye',
 'way',
 'www',
 'let',
 'prize',
 'feel',
 'right',
 'even',
 'tomorrow',
 'win',
 'alreadi',
 'pick',
 'tone',
 'said',
 'cash',
 'care',
 'im',
 'amp',
 'yeah',
 'leav',
 'realli',
 'babe',
 'find',
 'life',
 'morn',
 'last',
 'sleep',
 'keep',
 'servic',
 'year',
 'uk',
 'sure',
 'nokia',
 'would',
 'anyth',
 'buy',
 'use',
 'com',
 'start',
 'lol',
 'c

In [34]:
model.epochs

5

In [35]:
model.wv.similar_by_word('hope')

[('even', 0.9997615218162537),
 ('im', 0.9997497200965881),
 ('make', 0.9997453093528748),
 ('thing', 0.9997259378433228),
 ('said', 0.9997217655181885),
 ('one', 0.9997209310531616),
 ('come', 0.9997125267982483),
 ('much', 0.9997121691703796),
 ('day', 0.9997120499610901),
 ('love', 0.9997096061706543)]

In [36]:
import numpy as np
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key], axis = 0)

In [37]:
from tqdm import tqdm

In [38]:
type(model.wv.index_to_key)

list

In [39]:
x = []
for i in tqdm(range(len(words))):
    x.append(avg_word2vec(words[i]))

100%|██████████| 5564/5564 [00:00<00:00, 6999.14it/s]


In [40]:
type(x)

list

In [41]:
x_new = np.array(x)

In [42]:
x_new

array([array([-0.17441843,  0.23597042,  0.1181614 , -0.00488206,  0.08607417,
              -0.46318308,  0.1148792 ,  0.48946503, -0.12427697, -0.13816972,
              -0.10702524, -0.41016993, -0.08313604,  0.04635246,  0.095938  ,
              -0.14474197,  0.00482399, -0.26658082, -0.06060438, -0.4855421 ,
               0.14128144,  0.18670003,  0.05661864, -0.05234688, -0.08967509,
              -0.0451667 , -0.1971252 , -0.23189215, -0.20780039,  0.0902312 ,
               0.28643832,  0.09444515,  0.08962987, -0.14239064, -0.11109232,
               0.19932504,  0.02369961, -0.17139803, -0.15161096, -0.5653474 ,
               0.09108985, -0.19983017, -0.13695182,  0.03148245,  0.2475006 ,
              -0.12910683, -0.1456407 , -0.06770562,  0.19023345,  0.18244387,
               0.10472397, -0.30111203, -0.05969295,  0.04625881, -0.12405017,
               0.18082996,  0.11863878, -0.02319529, -0.20605157,  0.01684107,
               0.12793727,  0.15504687, -0.08513398,

In [43]:
type(x_new)

numpy.ndarray

In [44]:
words[0]

['go',
 'jurong',
 'point',
 'crazi',
 'avail',
 'bugi',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amor',
 'wat']

In [45]:
x_new[0]

array([-0.17441843,  0.23597042,  0.1181614 , -0.00488206,  0.08607417,
       -0.46318308,  0.1148792 ,  0.48946503, -0.12427697, -0.13816972,
       -0.10702524, -0.41016993, -0.08313604,  0.04635246,  0.095938  ,
       -0.14474197,  0.00482399, -0.26658082, -0.06060438, -0.4855421 ,
        0.14128144,  0.18670003,  0.05661864, -0.05234688, -0.08967509,
       -0.0451667 , -0.1971252 , -0.23189215, -0.20780039,  0.0902312 ,
        0.28643832,  0.09444515,  0.08962987, -0.14239064, -0.11109232,
        0.19932504,  0.02369961, -0.17139803, -0.15161096, -0.5653474 ,
        0.09108985, -0.19983017, -0.13695182,  0.03148245,  0.2475006 ,
       -0.12910683, -0.1456407 , -0.06770562,  0.19023345,  0.18244387,
        0.10472397, -0.30111203, -0.05969295,  0.04625881, -0.12405017,
        0.18082996,  0.11863878, -0.02319529, -0.20605157,  0.01684107,
        0.12793727,  0.15504687, -0.08513398, -0.07514327, -0.2865363 ,
        0.25002936,  0.12688507,  0.24588819, -0.36375186,  0.22